modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    #logoFile="examplemod.png"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc"
    mandatory=true
    versionRange="${tfc_version_range}"
    ordering="NONE"
    side="BOTH"
